/**
 * Email notification helper for enrollment submissions.
 * Uses Resend (https://resend.com) to forward each submission
 * to hello@mojakids.com.
 *
 * Requires RESEND_API_KEY environment variable.
 * If the key is missing the function logs a warning and returns false
 * so the rest of the submission flow is never blocked.
 */

import { Resend } from "resend";

const NOTIFY_TO = "hello@mojakids.com";
// Using Resend's shared domain until mojakids.com is verified at resend.com/domains
const FROM_ADDRESS = "Camp Moja Enrollment <onboarding@resend.dev>";

function getClient(): Resend | null {
  const key = process.env.RESEND_API_KEY;
  if (!key) {
    console.warn("[Email] RESEND_API_KEY is not set — skipping email notification.");
    return null;
  }
  return new Resend(key);
}

export type EnrollmentEmailPayload = {
  subject: string;
  /** Plain-text fallback */
  text: string;
  /** HTML body */
  html: string;
};

export async function sendEnrollmentEmail(
  payload: EnrollmentEmailPayload
): Promise<boolean> {
  const client = getClient();
  if (!client) return false;

  try {
    const { error } = await client.emails.send({
      from: FROM_ADDRESS,
      to: [NOTIFY_TO],
      subject: payload.subject,
      text: payload.text,
      html: payload.html,
    });

    if (error) {
      console.warn("[Email] Resend returned an error:", error);
      return false;
    }

    return true;
  } catch (err) {
    console.warn("[Email] Failed to send enrollment email:", err);
    return false;
  }
}

// ── HTML template helpers ──────────────────────────────────────────────────────

function row(label: string, value: string | undefined | null): string {
  if (!value) return "";
  return `
    <tr>
      <td style="padding:6px 12px 6px 0;color:#355574;font-weight:700;white-space:nowrap;vertical-align:top;font-size:13px;">${label}</td>
      <td style="padding:6px 0;color:#4a5568;font-size:13px;">${value}</td>
    </tr>`;
}

function section(title: string, rows: string): string {
  return `
    <div style="margin-bottom:24px;">
      <div style="background:#355574;color:white;font-weight:700;font-size:13px;letter-spacing:.05em;text-transform:uppercase;padding:6px 14px;border-radius:6px 6px 0 0;">${title}</div>
      <table style="width:100%;border-collapse:collapse;background:#f9fafb;border:1px solid #e2e8f0;border-top:none;border-radius:0 0 6px 6px;padding:8px 14px;">
        <tbody>${rows}</tbody>
      </table>
    </div>`;
}

function wrapHtml(formType: string, accentColor: string, body: string): string {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8" /></head>
<body style="margin:0;padding:0;background:#f0f4f8;font-family:Arial,sans-serif;">
  <div style="max-width:600px;margin:32px auto;background:white;border-radius:12px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,.08);">
    <div style="background:${accentColor};padding:20px 28px;">
      <p style="margin:0;color:white;font-size:11px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;opacity:.8;">Moja Kids Summer Camp 2026</p>
      <h1 style="margin:4px 0 0;color:white;font-size:22px;font-weight:700;">${formType}</h1>
    </div>
    <div style="padding:28px;">
      ${body}
      <p style="margin-top:28px;font-size:11px;color:#a0aec0;border-top:1px solid #e2e8f0;padding-top:16px;">
        This notification was automatically generated by the Moja Kids Summer Camp enrollment hub.<br>
        Reply to this email or contact the family directly using the details above.
      </p>
    </div>
  </div>
</body>
</html>`;
}

// ── Per-form email builders ────────────────────────────────────────────────────

export function buildClientEnrollmentEmail(input: {
  childFirstName: string;
  childLastName: string;
  childAge: string;
  childGender?: string | null;
  parentName: string;
  parentEmail: string;
  parentPhone: string;
  tshirtSize?: string | null;
  plannedAbsences: string;
  emergencyName: string;
  emergencyPhone: string;
  emergencyRelationship?: string | null;
  accommodations?: string | null;
  additionalNotes?: string | null;
  consentMedia?: string | null;
  consentLiability?: string | null;
}): EnrollmentEmailPayload {
  const childName = `${input.childFirstName} ${input.childLastName}`;
  const subject = `New Client Enrollment: ${childName}`;

  const html = wrapHtml("Existing Client Enrollment", "#355574", `
    ${section("Child", row("Name", childName) + row("Age / DOB", input.childAge) + row("Gender", input.childGender) + row("T-Shirt Size", input.tshirtSize))}
    ${section("Parent / Guardian", row("Name", input.parentName) + row("Email", input.parentEmail) + row("Phone", input.parentPhone))}
    ${section("Attendance", row("Planned Absences", input.plannedAbsences))}
    ${section("Emergency Contact", row("Name", input.emergencyName) + row("Phone", input.emergencyPhone) + row("Relationship", input.emergencyRelationship))}
    ${section("Notes", row("Accommodations", input.accommodations) + row("Additional Notes", input.additionalNotes))}
    ${section("Consents", row("Photo / Media", input.consentMedia) + row("Liability", input.consentLiability))}
  `);

  const text = `New Client Enrollment: ${childName}\n\nParent: ${input.parentName}\nEmail: ${input.parentEmail}\nPhone: ${input.parentPhone}\nChild Age: ${input.childAge}\nT-Shirt: ${input.tshirtSize ?? "Not specified"}\nPlanned Absences: ${input.plannedAbsences}\nEmergency Contact: ${input.emergencyName} (${input.emergencyPhone})`;

  return { subject, html, text };
}

export function buildCommunityEnrollmentEmail(input: {
  childFirstName: string;
  childLastName: string;
  childAge: string;
  childGender?: string | null;
  childDob?: string | null;
  diagnosis?: string | null;
  autismDiagnosis?: string | null;
  parentName: string;
  parentEmail: string;
  parentPhone: string;
  address?: string | null;
  sessionPreference?: string | null;
  tshirtSize?: string | null;
  allergies?: string | null;
  medications?: string | null;
  communicationStyle?: string | null;
  sensoryNeeds?: string | null;
  behavioralSupports?: string | null;
  emergencyName: string;
  emergencyPhone: string;
  emergencyRelationship?: string | null;
  paymentMethod?: string | null;
  additionalNotes?: string | null;
}): EnrollmentEmailPayload {
  const childName = `${input.childFirstName} ${input.childLastName}`;
  const subject = `New Community Enrollment: ${childName}`;

  const html = wrapHtml("Community Camper Registration", "#df76b6", `
    ${section("Child", row("Name", childName) + row("Date of Birth", input.childDob) + row("Gender", input.childGender) + row("T-Shirt Size", input.tshirtSize))}
    ${section("Diagnosis", row("Primary Diagnosis", input.diagnosis) + row("Autism Diagnosis", input.autismDiagnosis))}
    ${section("Parent / Guardian", row("Name", input.parentName) + row("Email", input.parentEmail) + row("Phone", input.parentPhone) + row("Address", input.address))}
    ${section("Camp", row("Session", "Full Summer — July 13 – August 21, 2026") + row("Payment Method", input.paymentMethod))}
    ${section("Medical & Support", row("Allergies", input.allergies) + row("Medications", input.medications) + row("Communication Style", input.communicationStyle) + row("Sensory Needs", input.sensoryNeeds) + row("Behavioral Supports", input.behavioralSupports))}
    ${section("Emergency Contact", row("Name", input.emergencyName) + row("Phone", input.emergencyPhone) + row("Relationship", input.emergencyRelationship))}
    ${section("Notes", row("Additional Notes", input.additionalNotes))}
  `);

  const text = `New Community Enrollment: ${childName}\n\nParent: ${input.parentName}\nEmail: ${input.parentEmail}\nPhone: ${input.parentPhone}\nDOB: ${input.childDob ?? "Not specified"}\nAutism Diagnosis: ${input.autismDiagnosis ?? "Not specified"}\nPayment: ${input.paymentMethod ?? "Not specified"}`;

  return { subject, html, text };
}

export function buildNewClientEnrollmentEmail(input: {
  childFirstName: string;
  childLastName: string;
  childAge: string;
  childGender?: string | null;
  childDob?: string | null;
  autismDiagnosis?: string | null;
  parentName: string;
  parentEmail: string;
  parentPhone: string;
  servicesInterest?: string[] | null;
  sessionInterest?: string | null;
  insuranceProvider?: string | null;
  insuranceMemberId?: string | null;
  primaryConcerns?: string | null;
  additionalNotes?: string | null;
  consentIntake?: string | null;
}): EnrollmentEmailPayload {
  const childName = `${input.childFirstName} ${input.childLastName}`;
  const subject = `New Client + Camp Inquiry: ${childName}`;

  const services = (input.servicesInterest ?? []).join(", ") || "None selected";

  const html = wrapHtml("New Client + Camp Enrollment", "#e66d38", `
    ${section("Child", row("Name", childName) + row("Age", input.childAge) + row("Date of Birth", input.childDob) + row("Gender", input.childGender) + row("Autism Diagnosis", input.autismDiagnosis))}
    ${section("Parent / Guardian", row("Name", input.parentName) + row("Email", input.parentEmail) + row("Phone", input.parentPhone))}
    ${section("Services & Camp", row("Services Interested In", services) + row("Session Interest", input.sessionInterest))}
    ${section("Insurance", row("Provider", input.insuranceProvider) + row("Member ID", input.insuranceMemberId))}
    ${section("Clinical", row("Primary Concerns", input.primaryConcerns) + row("Additional Notes", input.additionalNotes))}
    ${section("Consent", row("Intake Consent", input.consentIntake))}
  `);

  const text = `New Client + Camp Inquiry: ${childName}\n\nParent: ${input.parentName}\nEmail: ${input.parentEmail}\nPhone: ${input.parentPhone}\nChild Age: ${input.childAge}\nAutism Diagnosis: ${input.autismDiagnosis ?? "Not specified"}\nServices: ${services}\nSession Interest: ${input.sessionInterest ?? "Not specified"}`;

  return { subject, html, text };
}
